export const AP_STATE_CODE = "28"

export const AP_DISTRICTS: Array<{ code: string; name: string }> = [
  { code: "745", name: "Alluri Sitharama Raju" },
  { code: "744", name: "Anakapalli" },
  { code: "502", name: "Ananthapuramu" },
  { code: "753", name: "Annamayya" },
  { code: "750", name: "Bapatla" },
  { code: "503", name: "Chittoor" },
  { code: "747", name: "Dr. B.R. Ambedkar Konaseema" },
  { code: "505", name: "East Godavari" },
  { code: "748", name: "Eluru" },
  { code: "506", name: "Guntur" },
  { code: "746", name: "Kakinada" },
  { code: "510", name: "Krishna" },
  { code: "511", name: "Kurnool" },
  { code: "790", name: "Markapuram" },
  { code: "755", name: "Nandyal" },
  { code: "749", name: "NTR" },
  { code: "751", name: "Palnadu" },
  { code: "743", name: "Parvathipuram Manyam" },
  { code: "791", name: "Polavaram" },
  { code: "517", name: "Prakasam" },
  { code: "519", name: "Srikakulam" },
  { code: "515", name: "Sri Potti Sriramulu Nellore" },
  { code: "754", name: "Sri Sathya Sai" },
  { code: "752", name: "Tirupati" },
  { code: "520", name: "Visakhapatnam" },
  { code: "521", name: "Vizianagaram" },
  { code: "523", name: "West Godavari" },
  { code: "504", name: "Y.S.R. Kadapa" },
]

export const AP_MANDALS: Record<string, Array<{ code: string; name: string }>> = {
  "745": [
    { code: "4845", name: "Ananthagiri" },
    { code: "4844", name: "Araku Valley" },
    { code: "4846", name: "Chintapalle" },
    { code: "4847", name: "Dumbriguda" },
    { code: "4848", name: "G.Madugula" },
    { code: "4849", name: "Hukumpeta" },
    { code: "4851", name: "Koyyuru" },
    { code: "4852", name: "Lambasingi" },
    { code: "4853", name: "Munchingiputtu" },
    { code: "4854", name: "Paderu" },
    { code: "4855", name: "Peddabayalu" },
    { code: "4856", name: "Ravikamatham" },
    { code: "4857", name: "Rolugunta" },
    { code: "4858", name: "Sapparla" },
    { code: "4859", name: "Seethanagaram" },
    { code: "4860", name: "Yetapaka" },
  ],
  "744": [
    { code: "4871", name: "Anakapalli" },
    { code: "4878", name: "Atchuthapuram" },
    { code: "4873", name: "Butchayyapeta" },
    { code: "4874", name: "Elamanchili" },
    { code: "4875", name: "Kasimkota" },
    { code: "4876", name: "Makavarapalem" },
    { code: "4877", name: "Munagapaka" },
    { code: "4872", name: "Nakkapalle" },
    { code: "4879", name: "Paravada" },
    { code: "4880", name: "Rambilli" },
    { code: "4881", name: "Rolugunta" },
    { code: "4879", name: "Yelamanchili" },
  ],
  "502": [
    { code: "", name: "Agali" },
    { code: "", name: "Amadagur" },
    { code: "5330", name: "Anantapur Rural" },
    { code: "5322", name: "Atmakur" },
    { code: "5318", name: "Beluguppa" },
    { code: "5307", name: "Bommanahal" },
    { code: "5320", name: "Brahmasamudram" },
    { code: "5329", name: "Bukkaray Samudram" },
    { code: "5324", name: "Gooty" },
    { code: "5323", name: "Guntakal" },
    { code: "5328", name: "Hindupur" },
    { code: "5325", name: "Kadiri" },
    { code: "5326", name: "Kanaganapalle" },
    { code: "5308", name: "Kanekal" },
    { code: "5309", name: "Kudair" },
    { code: "5310", name: "Narpala" },
    { code: "5319", name: "Obuladevaracheruvu" },
    { code: "5311", name: "Pamidi" },
    { code: "5316", name: "Peddavadugur" },
    { code: "5314", name: "Putlur" },
    { code: "5315", name: "Rayadurgam" },
    { code: "5312", name: "Rolla" },
    { code: "5321", name: "Singanamala" },
    { code: "5317", name: "Tadimarri" },
    { code: "5313", name: "Talupula" },
    { code: "5317", name: "Uravakonda" },
    { code: "5316", name: "Vajrakarur" },
    { code: "5308", name: "Vidapanakal" },
    { code: "5312", name: "Yadiki" },
    { code: "5327", name: "Yellanur" },
  ],
  "503": [
    { code: "5423", name: "Baireddipalle" },
    { code: "5429", name: "Bangarupalem" },
    { code: "5410", name: "Chandragiri" },
    { code: "5406", name: "Chittoor" },
    { code: "5425", name: "Gangadhara Nellore" },
    { code: "5411", name: "Gudipala" },
    { code: "5412", name: "Irala" },
    { code: "5426", name: "Kuppam" },
    { code: "5427", name: "Madanapalle" },
    { code: "5428", name: "Nagalapuram" },
    { code: "5413", name: "Narayanavanam" },
    { code: "5414", name: "Pakala" },
    { code: "5422", name: "Palamaneru" },
    { code: "5424", name: "Palamaner Rural" },
    { code: "5415", name: "Pichatur" },
    { code: "5416", name: "Pileru" },
    { code: "5417", name: "Punganur" },
    { code: "5418", name: "Putalapattu" },
    { code: "5419", name: "Ramakuppam" },
    { code: "5420", name: "Renigunta" },
    { code: "5421", name: "Satyavedu" },
    { code: "5407", name: "Srirangarajapuram" },
    { code: "5408", name: "Thamballapalle" },
    { code: "5397", name: "Vedurukuppam" },
    { code: "5424", name: "Venkatagirikota" },
    { code: "5405", name: "Vijayapuram" },
    { code: "5430", name: "Yadamarri" },
  ],
  "505": [
    { code: "4887", name: "Addateegala" },
    { code: "", name: "Ainavilli" },
    { code: "", name: "Alamuru" },
    { code: "4917", name: "Anaparthi" },
    { code: "4916", name: "Biccavolu" },
    { code: "4959", name: "Chagallu" },
    { code: "4910", name: "Gangavaram" },
    { code: "4911", name: "Gokavaram" },
    { code: "4912", name: "I.Polavaram" },
    { code: "4913", name: "Jaggampeta" },
    { code: "4914", name: "Kadiam" },
    { code: "4915", name: "Kothapeta" },
    { code: "4918", name: "Malkipuram" },
    { code: "4919", name: "Mandapeta" },
    { code: "4920", name: "Peddapuram" },
    { code: "4921", name: "Prathipadu" },
    { code: "4922", name: "Rajam" },
    { code: "4923", name: "Rajole" },
    { code: "4924", name: "Ramachandrapuram" },
    { code: "4925", name: "Rangampeta" },
    { code: "4926", name: "Ravulapalem" },
    { code: "4927", name: "Rayavaram" },
    { code: "4928", name: "Rajanagaram" },
    { code: "4929", name: "Samalkota" },
    { code: "4930", name: "Sankhavaram" },
    { code: "4931", name: "Tallarevu" },
    { code: "4932", name: "Thondangi" },
    { code: "4933", name: "Tuni" },
    { code: "", name: "U.Kothapalli" },
    { code: "4970", name: "Undrajavaram" },
    { code: "4893", name: "Yeleswaram" },
  ],
  "748": [
    { code: "5005", name: "Agiripalli" },
    { code: "4963", name: "Bhimadole" },
    { code: "4948", name: "Buttayagudem" },
    { code: "5006", name: "Chintalapudi" },
    { code: "5007", name: "Denduluru" },
    { code: "5008", name: "Eluru Rural" },
    { code: "5009", name: "Ganapavaram" },
    { code: "5010", name: "Jangareddigudem" },
    { code: "5011", name: "Kamavarapukota" },
    { code: "5012", name: "Lingapalem" },
    { code: "5013", name: "Nallajerla" },
    { code: "5014", name: "Nidadavole" },
    { code: "5015", name: "Nuzvid Rural" },
    { code: "5016", name: "Palakoderu" },
    { code: "5017", name: "Pedavegi" },
    { code: "5018", name: "Poranki" },
    { code: "5019", name: "T.Narasapuram" },
    { code: "5020", name: "Tadepalligudem" },
    { code: "4962", name: "Unguturu" },
    { code: "", name: "Undi" },
    { code: "4734", name: "Velairpadu" },
    { code: "", name: "Veeravasaram" },
  ],
  "506": [
    { code: "", name: "Atchampet" },
    { code: "", name: "Bapatla" },
    { code: "5071", name: "Chebrolu" },
    { code: "5072", name: "Chilakaluripet" },
    { code: "5073", name: "Dachepalle" },
    { code: "5074", name: "Duggirala" },
    { code: "5075", name: "Guntur Urban" },
    { code: "5076", name: "Guntur Rural" },
    { code: "5077", name: "Macherla" },
    { code: "5078", name: "Mangalagiri" },
    { code: "5079", name: "Narasaraopet" },
    { code: "5080", name: "Ponnur" },
    { code: "5081", name: "Prathipadu" },
    { code: "5082", name: "Repalle" },
    { code: "5083", name: "Sattenapalle" },
    { code: "5084", name: "Tenali" },
    { code: "5080", name: "Vatticherukuru" },
  ],
  "746": [
    { code: "", name: "Kakinada Rural" },
    { code: "", name: "Kakinada Urban" },
    { code: "", name: "Peddapuram" },
    { code: "", name: "Prathipadu" },
    { code: "", name: "Ramachandrapuram" },
    { code: "4912", name: "U.Kothapalli" },
    { code: "4893", name: "Yeleswaram" },
  ],
  "510": [
    { code: "5037", name: "Avanigadda" },
    { code: "5019", name: "Bantumilli" },
    { code: "5004", name: "Bapulapadu" },
    { code: "5023", name: "Chandarlapadu" },
    { code: "", name: "Chatrai" },
    { code: "", name: "G.Konduru" },
    { code: "5025", name: "Gannavaram" },
    { code: "5026", name: "Gudivada" },
    { code: "5027", name: "Gudlavalleru" },
    { code: "5028", name: "Ibrahimpatnam" },
    { code: "5029", name: "Jaggayyapeta" },
    { code: "5030", name: "Kankipadu" },
    { code: "5031", name: "Koduru" },
    { code: "5032", name: "Kruthivennu" },
    { code: "5033", name: "Machilipatnam" },
    { code: "5034", name: "Mopidevi" },
    { code: "5035", name: "Mudinepalli" },
    { code: "5036", name: "Mylavaram" },
    { code: "5037", name: "Nagayalanka" },
    { code: "5038", name: "Nandigama" },
    { code: "5039", name: "Nuzividu" },
    { code: "5040", name: "Pamidimukkala" },
    { code: "5041", name: "Pamarru" },
    { code: "5042", name: "Pedana" },
    { code: "5043", name: "Penamaluru" },
    { code: "5044", name: "Tiruvuru" },
    { code: "5013", name: "Unguturu" },
    { code: "4994", name: "Veerullapadu" },
    { code: "", name: "Vissannapeta" },
    { code: "5027", name: "Vuyyuru" },
  ],
  "511": [
    { code: "5271", name: "Adoni" },
    { code: "5274", name: "Alur" },
    { code: "5275", name: "Aspari" },
    { code: "5265", name: "Atmakur" },
    { code: "5283", name: "Bandi Atmakur" },
    { code: "5256", name: "C.Belagal" },
    { code: "5303", name: "Chagalamarri" },
    { code: "5257", name: "Dhone" },
    { code: "5258", name: "Dornipadu" },
    { code: "5259", name: "Gospadu" },
    { code: "5260", name: "Gudur" },
    { code: "5261", name: "Holagunda" },
    { code: "5262", name: "Kallur" },
    { code: "5263", name: "Kodumur" },
    { code: "5264", name: "Kolimigundla" },
    { code: "5266", name: "Kurnool Rural" },
    { code: "5267", name: "Maddikera" },
    { code: "5268", name: "Mantralayam" },
    { code: "5269", name: "Nandyal Rural" },
    { code: "5270", name: "Nandikotkur" },
    { code: "5272", name: "Orvakal" },
    { code: "5273", name: "Panyam" },
    { code: "5276", name: "Pamulapadu" },
    { code: "5277", name: "Pathikonda" },
    { code: "5278", name: "Peapully" },
    { code: "5279", name: "Srisailam" },
    { code: "5280", name: "Sanjamala" },
    { code: "5302", name: "Uyyalawada" },
    { code: "5281", name: "Velgode" },
    { code: "5278", name: "Veldurthy" },
    { code: "5254", name: "Yemmiganur" },
  ],
  "517": [
    { code: "5112", name: "Addanki" },
    { code: "5105", name: "Ballikurava" },
    { code: "5106", name: "Chimakurthy" },
    { code: "5107", name: "Cumbum" },
    { code: "5108", name: "Darsi" },
    { code: "5109", name: "Dornala" },
    { code: "5110", name: "Giddalur" },
    { code: "5111", name: "Inkollu" },
    { code: "5113", name: "Kandukur" },
    { code: "5114", name: "Kanigiri" },
    { code: "5115", name: "Komarolu" },
    { code: "5116", name: "Korisapadu" },
    { code: "5117", name: "Kothapatnam" },
    { code: "5118", name: "Kurichedu" },
    { code: "", name: "Mangalagiri" },
    { code: "5119", name: "Markapuram" },
    { code: "5120", name: "Mundlamuru" },
    { code: "5121", name: "Naguluppalapadu" },
    { code: "5122", name: "Parchur" },
    { code: "5123", name: "Podili" },
    { code: "5124", name: "Pullalacheruvu" },
    { code: "5125", name: "Racherla" },
    { code: "5126", name: "Santamagalur" },
    { code: "5127", name: "Singarayakonda" },
    { code: "5128", name: "Tangutur" },
    { code: "5129", name: "Tripuranthakam" },
    { code: "5152", name: "Ulavapadu" },
    { code: "5124", name: "Vetapalem" },
    { code: "5147", name: "Voletivaripalem" },
    { code: "", name: "Yarragondapalem" },
    { code: "5142", name: "Zarugumalli" },
  ],
  "519": [
    { code: "4798", name: "Amadalavalasa" },
    { code: "4794", name: "Burja" },
    { code: "4795", name: "Etcherla" },
    { code: "4796", name: "G.Sigadam" },
    { code: "4797", name: "Gara" },
    { code: "4799", name: "Hiramandalam" },
    { code: "4800", name: "Ichchapuram" },
    { code: "4801", name: "Jalumuru" },
    { code: "4802", name: "Kanchili" },
    { code: "4803", name: "Kaviti" },
    { code: "4804", name: "Kotabommali" },
    { code: "4805", name: "Kothuru" },
    { code: "4806", name: "Laveru" },
    { code: "4807", name: "Mandasa" },
    { code: "4808", name: "Meliaputti" },
    { code: "4809", name: "Narasannapeta" },
    { code: "4810", name: "Palakonda" },
    { code: "4811", name: "Pathapatnam" },
    { code: "4812", name: "Polaki" },
    { code: "4813", name: "Rajam" },
    { code: "4814", name: "Ranastalam" },
    { code: "4815", name: "Saravakota" },
    { code: "4816", name: "Sarubujjili" },
    { code: "4817", name: "Srikakulam Rural" },
    { code: "4818", name: "Tekkali" },
    { code: "4781", name: "Vajrapukotturu" },
    { code: "4785", name: "Vangara" },
  ],
  "515": [
    { code: "5167", name: "Allur" },
    { code: "5173", name: "Ananthasagaram" },
    { code: "5165", name: "Anumasamudrampeta" },
    { code: "5164", name: "Atmakur" },
    { code: "5159", name: "Bogole" },
    { code: "", name: "Brahmasamudram" },
    { code: "5170", name: "Buchireddipalem" },
    { code: "5166", name: "Kavali" },
    { code: "5171", name: "Kodavalur" },
    { code: "5172", name: "Kondapuram" },
    { code: "5162", name: "Marripadu" },
    { code: "5163", name: "Naidupeta" },
    { code: "5169", name: "Nellore Rural" },
    { code: "5174", name: "Ojili" },
    { code: "5175", name: "Pellakur" },
    { code: "5176", name: "Podalakur" },
    { code: "5177", name: "Sarvepalli" },
    { code: "5178", name: "Sydapuram" },
    { code: "5179", name: "T.P.Gudur" },
    { code: "5180", name: "Udayagiri" },
    { code: "5192", name: "Vakadu" },
    { code: "5155", name: "Varikuntapadu" },
    { code: "5182", name: "Venkatachalam" },
    { code: "5168", name: "Vidavalur" },
    { code: "5161", name: "Vinjamur" },
  ],
  "754": [
    { code: "5354", name: "Agali" },
    { code: "5361", name: "Amadagur" },
    { code: "5351", name: "Amarapuram" },
    { code: "5337", name: "Bathalapalli" },
    { code: "5345", name: "Bukkapatnam" },
    { code: "", name: "Kadiri" },
    { code: "", name: "Mudigubba" },
    { code: "", name: "Obuladevaracheruvu" },
    { code: "", name: "Puttaparthi" },
    { code: "", name: "Tanakal" },
    { code: "", name: "Uravakonda" },
  ],
  "752": [
    { code: "5188", name: "Balayapalli" },
    { code: "5380", name: "Buchinaidu Kandriga" },
    { code: "", name: "Chandragiri" },
    { code: "", name: "Chittoor" },
    { code: "", name: "Srikalahasti" },
    { code: "5196", name: "Tirupati Rural" },
    { code: "", name: "Tirupati Urban" },
    { code: "5399", name: "Vadamalapet" },
    { code: "5381", name: "Varadaiahpalem" },
    { code: "5187", name: "Venkatagiri" },
    { code: "5377", name: "Yerpedu" },
    { code: "5374", name: "Yerravaripalem" },
  ],
  "520": [
    { code: "4863", name: "Anandapuram" },
    { code: "4865", name: "Bheemunipatnam" },
    { code: "4866", name: "Chodavaram" },
    { code: "", name: "Paderu" },
    { code: "", name: "Parawada" },
    { code: "4866", name: "Visakhapatnam Rural" },
    { code: "", name: "Visakhapatnam Urban" },
  ],
  "521": [
    { code: "4820", name: "Badangi" },
    { code: "4840", name: "Bhogapuram" },
    { code: "4816", name: "Bobbili" },
    { code: "4829", name: "Bondapalli" },
    { code: "4821", name: "Gajapathinagaram" },
    { code: "4822", name: "Gantyada" },
    { code: "4823", name: "Gurla" },
    { code: "4824", name: "Jami" },
    { code: "4825", name: "Kothavalasa" },
    { code: "4826", name: "Lakkavarapukota" },
    { code: "4827", name: "Makkuva" },
    { code: "4828", name: "Mentada" },
    { code: "4830", name: "Merakamudidam" },
    { code: "4831", name: "Pachipenta" },
    { code: "4810", name: "Palakonda" },
    { code: "4832", name: "Parvathipuram" },
    { code: "4833", name: "Pusapatirega" },
    { code: "4834", name: "Rajam" },
    { code: "4835", name: "Salur" },
    { code: "4836", name: "Srungavarapukota" },
    { code: "4832", name: "Vepada" },
    { code: "4836", name: "Vizianagaram Rural" },
  ],
  "523": [
    { code: "4981", name: "Achanta" },
    { code: "4975", name: "Akividu" },
    { code: "4973", name: "Attili" },
    { code: "4984", name: "Bhimavaram" },
    { code: "", name: "Bhimavaram Rural" },
    { code: "", name: "Chintalapudi" },
    { code: "", name: "Denduluru" },
    { code: "", name: "Eluru" },
    { code: "", name: "Ganapavaram" },
    { code: "", name: "Jangareddigudem" },
    { code: "", name: "Kamavarapukota" },
    { code: "4985", name: "Kovvur" },
    { code: "", name: "Kovvur Rural" },
    { code: "4986", name: "Narasapuram" },
    { code: "4987", name: "Nidadavole" },
    { code: "4988", name: "Palacole" },
    { code: "4989", name: "Penumantra" },
    { code: "", name: "Tadepalligudem" },
    { code: "4990", name: "Tanuku" },
    { code: "4976", name: "Undi" },
    { code: "", name: "Unguturu" },
    { code: "4983", name: "Veeravasaram" },
  ],
  "504": [
    { code: "5227", name: "Atlur" },
    { code: "5209", name: "B.Kodur" },
    { code: "5210", name: "Badvel" },
    { code: "5205", name: "Brahmamgarimattam" },
    { code: "5211", name: "Chakrayapet" },
    { code: "5212", name: "Chinnamandem" },
    { code: "5213", name: "Cuddapah Rural" },
    { code: "5214", name: "Duvvur" },
    { code: "5215", name: "Galiveedu" },
    { code: "5216", name: "Jammalamadugu" },
    { code: "5217", name: "Kamalapuram" },
    { code: "5218", name: "Khajipeta" },
    { code: "5219", name: "Kodur" },
    { code: "5220", name: "Kondapuram" },
    { code: "5221", name: "Lakkireddipalli" },
    { code: "5222", name: "Lingala" },
    { code: "5223", name: "Mydukur" },
    { code: "5224", name: "Nandalur" },
    { code: "5225", name: "Proddatur" },
    { code: "5226", name: "Pulivendla" },
    { code: "5228", name: "Rajampet" },
    { code: "5229", name: "Rayachoti" },
    { code: "", name: "Rajnampet" },
    { code: "5230", name: "Siddhavattam" },
    { code: "5231", name: "Sidhout" },
    { code: "5232", name: "Simhadripuram" },
    { code: "5233", name: "Vempalli" },
    { code: "5228", name: "Vontimitta" },
    { code: "5222", name: "Veerapunayunipalle" },
    { code: "5223", name: "Yerraguntla" },
  ],
  "747": [
    { code: "4933", name: "Ainavilli" },
    { code: "4925", name: "Alamuru" },
    { code: "4940", name: "Allavaram" },
    { code: "4941", name: "Amalapuram" },
    { code: "4935", name: "Ambajipeta" },
    { code: "4919", name: "Atreyapuram" },
    { code: "4943", name: "Katrenikona" },
    { code: "4944", name: "Mamidikuduru" },
    { code: "4945", name: "Malikipuram" },
    { code: "4946", name: "Mummidivaram" },
    { code: "4947", name: "Mulapeta" },
    { code: "4948", name: "Razole" },
    { code: "", name: "Ravulapalem" },
    { code: "4949", name: "Sakhinetipalle" },
    { code: "4942", name: "Uppalaguptam" },
    { code: "4950", name: "Uppe" },
    { code: "4951", name: "Yanam" },
  ],
  "749": [
    { code: "4998", name: "Atlapragada Konduru" },
    { code: "4999", name: "Gampalagudem" },
    { code: "", name: "Ibrahimpatnam" },
    { code: "", name: "Jaggayyapeta" },
    { code: "", name: "Mylavaram" },
    { code: "", name: "Nandigama" },
    { code: "5010", name: "Vijayawada Central" },
    { code: "5011", name: "Vijayawada Rural" },
    { code: "5000", name: "Vissannapeta" },
    { code: "4990", name: "Vatsavai" },
    { code: "4994", name: "Veerullapadu" },
  ],
  "751": [
    { code: "5052", name: "Amaravathi" },
    { code: "5050", name: "Atchampet" },
    { code: "5049", name: "Bellamkonda" },
    { code: "5061", name: "Bollapalli" },
    { code: "", name: "Dachepalle" },
    { code: "5053", name: "Gurazala" },
    { code: "5054", name: "Karampudi" },
    { code: "5055", name: "Macherla" },
    { code: "", name: "Narasaraopet" },
    { code: "5056", name: "Piduguralla" },
    { code: "5057", name: "Rentachintala" },
    { code: "", name: "Sattenapalle" },
    { code: "", name: "Velgode" },
    { code: "5041", name: "Veldurthy" },
    { code: "5062", name: "Vinukonda" },
  ],
  "743": [
    { code: "4815", name: "Balijipeta" },
    { code: "4771", name: "Bhamini" },
    { code: "", name: "Gajapathinagaram" },
    { code: "4772", name: "Kurupam" },
    { code: "", name: "Makkuva" },
    { code: "", name: "Parvathipuram" },
    { code: "", name: "Salur" },
    { code: "4773", name: "Seethampeta" },
    { code: "4769", name: "Veeraghattam" },
  ],
  "791": [
    { code: "4887", name: "Addateegala" },
    { code: "4733", name: "Kunavaram" },
    { code: "4733", name: "Vararamachandrapuram" },
    { code: "4886", name: "Y.Ramavaram" },
    { code: "6063", name: "Yetapaka" },
  ],
  "790": [
    { code: "5116", name: "Ardhaveedu" },
    { code: "5131", name: "Bestavaripeta" },
    { code: "", name: "Dornala" },
    { code: "", name: "Giddalur" },
    { code: "", name: "Komarolu" },
    { code: "5097", name: "Markapuram" },
    { code: "5135", name: "Veligandla" },
    { code: "5097", name: "Yerragondapalem" },
  ],
  "755": [
    { code: "5298", name: "Allagadda" },
    { code: "5298", name: "Atmakur" },
    { code: "5288", name: "Banaganapalli" },
    { code: "5283", name: "Bandi Atmakur" },
    { code: "5279", name: "Bethamcherla" },
    { code: "5303", name: "Chagalamarri" },
    { code: "", name: "Gospadu" },
    { code: "", name: "Kolimigundla" },
    { code: "5269", name: "Nandyal Rural" },
    { code: "", name: "Peapully" },
    { code: "", name: "Srisailam" },
    { code: "5302", name: "Uyyalawada" },
    { code: "5282", name: "Velgodu" },
  ],
  "753": [
    { code: "5391", name: "Beerongi Kothakota" },
    { code: "", name: "Madanapalle" },
    { code: "", name: "Obulavaripalle" },
    { code: "", name: "Pileru" },
    { code: "", name: "Rajampet" },
    { code: "", name: "Rayachoti" },
    { code: "5388", name: "Valmikipuram" },
  ],
}
